# Generated by Django 2.2.2 on 2019-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190805_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(editable=False),
        ),
    ]
