# Generated by Django 2.2.2 on 2019-08-05 13:33

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190802_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contect',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
