# Generated by Django 2.2.2 on 2019-08-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190805_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='sessions',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
